"""Detection signals for Provenance Guard.

Signal 1 — LLM judge (Groq, llama-3.3-70b-versatile).
Returns an AI-probability in [0, 1] plus a one-line rationale.
(Signal 2 — stylometric heuristics — lives below as a stub for now.)
"""

import json
import os
import re
import statistics

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _client


_SYSTEM_PROMPT = (
    "You are an AI text detector. You will be given a section of text. "
    "Judge how likely it is that the passage was generated by an AI language "
    "model rather than written by a human. Consider semantic cues that simple "
    "statistics miss: generic content, even/uniform hedging, lack of specific "
    "lived detail, and the recognizable 'voice' of aligned models. "
    "Respond with ONLY a JSON object, no extra text, in exactly this shape:\n"
    '{"ai_probability": <float between 0 and 1>, "rationale": "<one short sentence>"}'
)


def signal_llm(text):
    """Signal 1: ask a Groq LLM how AI-generated the text reads.

    Args:
        text: the raw submitted text.

    Returns:
        dict: {"ai_probability": float in [0, 1], "rationale": str}.
        On API/parse failure, returns ai_probability 0.5 with an error rationale
        so the caller can degrade gracefully rather than crash.
    """
    try:
        completion = _get_client().chat.completions.create(
            model=GROQ_MODEL,
            temperature=0,  # deterministic-ish: we want a stable judgment
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = completion.choices[0].message.content or "{}"
        data = json.loads(raw)

        # Clamp to [0, 1] in case the model returns something out of range.
        prob = float(data.get("ai_probability", 0.5))
        prob = max(0.0, min(1.0, prob))
        rationale = str(data.get("rationale", "")
                        ).strip() or "No rationale provided."

        return {"ai_probability": prob, "rationale": rationale}

    except Exception as exc:  # noqa: BLE001 - degrade gracefully on any failure
        return {
            "ai_probability": 0.5,
            "rationale": f"LLM signal unavailable ({exc}); defaulted to 0.5.",
        }


# Phrases over-represented in default instruction-tuned LLM output. Presence
# pushes toward AI; absence is uninformative (kept neutral, not pro-human).
_BOILERPLATE = [
    "delve", "it's important to note", "it is important to note",
    "moreover", "furthermore", "in today's world", "in the modern era",
    "tapestry", "navigate the complexities", "a testament to",
    "plays a crucial role", "plays a vital role", "plays a significant role",
    "when it comes to", "in conclusion", "leveraging", "underscores",
    "fast-paced world", "unlock", "realm of",
]


def _clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


def _words(text):
    """Lowercase word tokens (letters/apostrophes only)."""
    return re.findall(r"[a-z']+", text.lower())


def _sentences(text):
    """Non-empty sentence chunks split on . ! ? boundaries."""
    return [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]


def signal_stylometric(text):
    """Signal 2: local, deterministic stylometric heuristics.

    Combines three sub-features, each expressed as an AI-leaning score in [0,1]:
      - burstiness: low sentence-length variance -> AI-like
      - lexical diversity (type-token ratio): low diversity -> AI-like
      - boilerplate density: more AI-favored phrases -> AI-like

    Returns:
        dict: {"ai_probability": float in [0, 1]}.
    """
    words = _words(text)
    n_words = len(words)
    if n_words == 0:
        return {"ai_probability": 0.5}

    # --- burstiness: coefficient of variation of sentence word-counts -----
    sent_lengths = [len(_words(s)) for s in _sentences(text)]
    sent_lengths = [n for n in sent_lengths if n > 0]
    if len(sent_lengths) >= 2 and statistics.mean(sent_lengths) > 0:
        cv = statistics.pstdev(sent_lengths) / statistics.mean(sent_lengths)
        # cv 0 -> 1.0 (AI); cv>=0.7 -> 0
        burstiness_ai = _clamp(1.0 - cv / 0.7)
    else:
        burstiness_ai = 0.5  # too few sentences to judge

    # --- lexical diversity: type-token ratio (unique / total) -------------
    ttr = len(set(words)) / n_words
    ttr_ai = _clamp((0.7 - ttr) / (0.7 - 0.4))  # ttr>=0.7 -> 0; ttr<=0.4 -> 1

    # --- boilerplate density (high-precision AI tell) ---------------------
    # Count DISTINCT AI-favored phrases present (so one repeated word can't
    # spike it). Presence -> AI; absence -> neutral (0.5).
    low = text.lower()
    distinct_hits = sum(1 for p in _BOILERPLATE if p in low)
    boilerplate_ai = _clamp(0.5 + 0.17 * distinct_hits)  # 3 distinct -> ~1.0

    ai_probability = (
        0.30 * burstiness_ai
        + 0.25 * ttr_ai
        + 0.45 * boilerplate_ai
    )

    # Stacked AI cliches are rare in human writing: 2+ distinct boilerplate
    # phrases floor the score high so it agrees with a confident LLM signal.
    if distinct_hits >= 2:
        ai_probability = max(ai_probability, 0.70)

    return {"ai_probability": round(_clamp(ai_probability), 4)}
